# Generated by Django 2.0.7 on 2018-08-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_tutorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='edu_qualification',
            field=models.CharField(default='', max_length=100),
        ),
    ]
