# Generated by Django 2.0.7 on 2018-08-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180808_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='description',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
