# Generated by Django 2.0.7 on 2018-08-10 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180810_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='charge_hr',
            field=models.IntegerField(default=100),
        ),
    ]
